package boundarycheck

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckDependencies_rejectsProviderDependency(t *testing.T) {
	const module = "example.com/agent"
	dependencies := []string{
		"context",
		module,
		module + "/provider/openairesponses",
	}

	err := CheckDependencies(module, dependencies)
	if !errors.Is(err, ErrProviderDependency) {
		t.Fatalf("CheckDependencies() error = %v, want ErrProviderDependency", err)
	}
	if !strings.Contains(err.Error(), module+"/provider/openairesponses") {
		t.Fatalf("error = %q, want offending dependency", err)
	}
}

func TestCheckDependencies_acceptsCoreDependencies(t *testing.T) {
	dependencies := []string{"context", "encoding/json", "example.com/agent"}
	if err := CheckDependencies("example.com/agent", dependencies); err != nil {
		t.Fatalf("CheckDependencies() error = %v", err)
	}
}

func TestCheckFileSizes_rejectsOversizedGoFile(t *testing.T) {
	root := t.TempDir()
	lines := make([]string, 1, 251)
	lines[0] = "package fixture"
	for index := range 250 {
		lines = append(lines, fmt.Sprintf("var value%d = %d", index, index))
	}
	path := filepath.Join(root, "oversized.go")
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	err := CheckFileSizes(root, 250)
	if !errors.Is(err, ErrFileTooLarge) {
		t.Fatalf("CheckFileSizes() error = %v, want ErrFileTooLarge", err)
	}
	var violation *ViolationError
	if !errors.As(err, &violation) {
		t.Fatalf("CheckFileSizes() error type = %T, want *ViolationError", err)
	}
	if violation.Actual != 251 || violation.Limit != 250 {
		t.Fatalf("violation = %+v, want actual 251 and limit 250", violation)
	}
}

func TestCheckFileSizes_ignoresCommentsAndGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	commentOnly := "package fixture\n" + strings.Repeat("// 说明\n", 300)
	generated := "// Code generated by fixture. DO NOT EDIT.\npackage fixture\n" +
		strings.Repeat("var generated = true\n", 300)
	writeFixture(t, filepath.Join(root, "comments.go"), commentOnly)
	writeFixture(t, filepath.Join(root, "generated.go"), generated)

	if err := CheckFileSizes(root, 250); err != nil {
		t.Fatalf("CheckFileSizes() error = %v", err)
	}
}

func TestCheckFileSizes_doesNotTrustGeneratedMarkerAfterPackage(t *testing.T) {
	root := t.TempDir()
	content := "package fixture\n// Code generated by fixture. DO NOT EDIT.\n" +
		strings.Repeat("var generated = true\n", 250)
	writeFixture(t, filepath.Join(root, "not_generated.go"), content)

	err := CheckFileSizes(root, 250)
	if !errors.Is(err, ErrFileTooLarge) {
		t.Fatalf("CheckFileSizes() error = %v, want ErrFileTooLarge", err)
	}
}

func writeFixture(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
}
